# Generated by Django 3.1.5 on 2026-03-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelfine',
            name='student_id_entered',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
